# portfolio/apps/cert-manager/values.yml
installCRDs: true

crds:
  enabled: true          # installs cert-manager CRDs automatically

replicaCount: 1

# Required for DNS-01 challenges to work correctly
extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53

resources:
  requests:
    cpu: 10m
    memory: 32Mi