linux:
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"
  hosts:
    portfolioctrl:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ control_plane_ip }}"
    portfoliowrkr0:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[0] }}"
    portfoliowrkr1:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[1] }}"

vms:
  hosts:
    portfolioctrl:
    portfoliowrkr0:
    portfoliowrkr1:

controllers:
  hosts:
    portfolioctrl:

workers:
  hosts:
    portfoliowrkr0:
    portfoliowrkr1:
