linux:
  hosts:
    portfolioctrl:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ control_plane_ip }}"
    portfoliowrkr0:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[0] }}"
    portfoliowrkr1:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[1] }}"
    portfoliowrkr2:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[2] }}"
    portfoliowrkr3:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[3] }}"
    #portfoliowrkr4:
    #  ansible_user: "{{ ssh_user }}"
    #  ansible_host: "{{ worker_ips[4] }}"

vms:
  hosts:
    portfolioctrl:
    portfoliowrkr0:
    portfoliowrkr1:
    portfoliowrkr2:
    portfoliowrkr3:
    #portfoliowrkr4:

controllers:
  hosts:
    portfolioctrl:

workers:
  hosts:
    portfoliowrkr0:
    portfoliowrkr1:
    portfoliowrkr2:
    portfoliowrkr3:
    #portfoliowrkr4:
